# in this RUN section we will keep default parameters
RUN:
  log_dir: "/tmp"
  run_id: null

# This section is related to ui testing with selenium
UI_SELENIUM:
  browser_type: "chrome"
  chrome_type: "google-chrome"
  headless: False
  screenshot: True
  ignore_ssl: True
  url: "http://192.168.99.101:5000/"