pipeline{
    /*A declarative pipeline*/
    agent {
        /*Agent section*/ 
        // where would you like to run the code 
        label 'master' 
        }
    options{
        timestamps()
        }
    parameters {
        string(name: 'TEST_PATH', description: 'test path')
        choice(name: 'MARKER', choices: ['tier1', 'tier2'], description: 'Choose test suite')
    }
    stages{
        /*stages section*/
        stage ('Clone Repository') {
            steps{
                echo "Git clone"
                git branch: 'main',
                    url: 'https://github.com/Oded1990/automation-infra.git'
                sh "ls -lat"
                sh "pwd"
            }  
        }
        
        stage ('Create Virtaul Environment'){
            steps{
                echo "Create venv"
                sh "python3 -m venv venv"
                sh """
                    . venv/bin/activate
                    pip install -r requirements.txt
                    deactivate
                    """
               
            }
        }
        
        stage ('Test'){
            steps{
                echo "Test"
                echo "test path:${params.TEST_PATH}"
                sh """
                    . venv/bin/activate
                    pytest ${params.TEST_PATH} -m ${params.MARK}
                    """
            }
        }
    } 
}
